pipeline {
    agent any

    environment {
        GIT_CREDENTIALS = 'github-token'         
        GIT_REPO_URL = 'https://github.com/Ivan1845/Kursova-SP.git'
    }

    stages {
        stage('Checkout') {
            steps {
                // Клонування репозиторію
                git url: "${GIT_REPO_URL}", credentialsId: "${GIT_CREDENTIALS}"
            }
        }

        stage('Build') {
            steps {
                // Збірка проекту за допомогою MSBuild
                bat '"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe" "C:\\git курсач\\Task 4\\vs_mkr_test1\\test_repos.sln" /t:Build /p:Configuration=Release'

            }
        }

        stage('Test') {
            steps {
                // Запуск тестів
                bat "x64\\Debug\\test_repos.exe --gtest_output=xml:test_report.xml"
            }
        }
    }

    post {
        always {
            // Публікація результатів тестів
            junit '**/test_report.xml'
        }
    }
}
